name: Changesets Automation

on:
  pull_request:
    types: [opened]

jobs:
  changesets-automation:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}
    timeout-minutes: 10
    steps:
      - name: Merge Changesets PR
        if: github.ref_name == "changeset-release/main"
        uses: "actions/github-script@v6"
        script: |
          console.log("Merge Changesets PR")
        
